### ISSUE TITLE
[Suggestion:]

### ISSUE THREAD

**Issue by arsinam80** [rafidalhaque/frontend-vscode-extensionpack#4]
### Extension Name

Morteza Shabani

### Extension ID

Morteza

### What the Extension do?

Good

### Any message?

Help

**Comment by arsinam80** [comment]
Good

**Comment by arsinam80** [comment]
J

**Comment by rafidalhaque** [comment]
Sorry, I couldn't understand. Can you describe it's functionality and how can I help you?
